base_model: google/gemma-2b-it
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: tatsu-lab/alpaca
    type: alpaca
val_set_size: 0.1

# datasets:
#   - path: glaiveai/glaive-function-calling-v2
#     type: sharegpt.load_glaive
#     split: train
#     conversation: chatml_glaive
# val_set_size: 0.1

dataset_prepared_path: ./prepared-datasets/gemma-glaive
output_dir: ./lora-out/gemma-glaive-sft

adapter: qlora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_target_modules:
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

wandb_project: gemma-2b-glaive

gradient_accumulation_steps: 3
micro_batch_size: 6
num_epochs: 25
optimizer: adamw_bnb_8bit
lr_scheduler: linear
learning_rate: 5e-5

train_on_inputs: false
group_by_length: false
bf16: auto

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
flash_attention: true

warmup_steps: 10
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
weight_decay: 0.0
evals_per_epoch: 4
eval_batch_size: 1
eval_sample_packing: false
fsdp:
fsdp_config:
special_tokens:
