base_model: google/gemma-1.1-2b-it
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

# huggingface repo
datasets:
  - path: garage-bAInd/Open-Platypus
    type: alpaca
val_set_size: 0.1
output_dir: ./out

adapter: qlora
lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true

sequence_len: 4096
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true


gradient_accumulation_steps: 3
micro_batch_size: 2
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002


train_on_inputs: false
group_by_length: false
bf16: auto

gradient_checkpointing: true
logging_steps: 1
flash_attention: true

warmup_ratio: 0.1
evals_per_epoch: 4
eval_table_size: 2
eval_batch_size: 2
eval_max_new_tokens: 64
saves_per_epoch: 1