base_model: google/gemma-1.1-2b-it
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
chat_template: gemma

load_in_8bit: false
load_in_4bit: true
strict: false

# datasets:
#   - path: tatsu-lab/alpaca
#     type: alpaca
# val_set_size: 0.1

datasets:
  - path: glaiveai/glaive-function-calling-v2
    type: sharegpt.load_glaive
    split: train
    conversation: gemma_glaive

val_set_size: 50

dataset_prepared_path: ./prepared-datasets/gemma-glaive-fc
output_dir: ./lora-out/gemma-glaive-sft

adapter: qlora
lora_r: 128
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true
lora_target_modules:
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

gradient_accumulation_steps: 2
micro_batch_size: 4
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: linear
learning_rate: 2e-4
warmup_steps: 10
weight_decay: 0.0

train_on_inputs: false
group_by_length: false
bf16: auto

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
flash_attention: true

eval_steps: 1000
eval_table_size: 2
eval_batch_size: 2
eval_sample_packing: false
eval_max_new_tokens: 32
do_causal_lm_eval: true
special_tokens:
  additional_special_tokens: ["<functioncall>"]

eval_causal_lm_metrics: ["tool_use_json", "sacrebleu", "chrf"]
