base_model: google/gemma-2-2b-it
trust_remote_code: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

wandb_name: gemnma_chat_template

disable_save_on_terminate: true
add_random_suffix_to_run_name: true
eval_print_special_tokens: true
output_dir: ./out/goody-dpo

chat_template: gemma
rl: dpo
datasets:
  - path: roborovski/open-goody2-dpo
    type: chat_template.default
    chat_template: gemma
    field_messages: conversation
    field_chosen: chosen
    field_rejected: rejected
    message_field_role: role
    message_field_content: content
    message_preprocessor: goody
    roles_to_train: ["assistant"]

dataset_prepared_path: ./prepared-datasets/goody-dpo
val_set_size: 4
shuffle_before_split: true

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: false

adapter: lora
lora_model_dir:
lora_r: 64
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true

micro_batch_size: 4
gradient_accumulation_steps: 2
num_epochs: 5
optimizer: adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-4

bf16: auto

seed: 1010101

gradient_checkpointing: true
logging_steps: 1
flash_attention: true

eval_steps: 100
save_steps: 5000
eval_table_size: 4
eval_batch_size: 4
eval_sample_packing: false
eval_max_new_tokens: 512
eval_causal_lm_metrics: ["perplexity", "ter"]
do_causal_lm_eval: true

warmup_steps: 10
weight_decay: 0.1
resize_token_embeddings_to_32x: true
