base_model: meta-llama/Llama-3.2-1B-Instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

strict: false

datasets:
  - path: SenseLLM/ReflectionSeq-DS
    type: chat_template
    chat_template: llama3
    field_messages: messages
    message_preprocessor: reflection_coder
    roles_to_train: ['user', 'assistant']
    split: train

val_set_size: 50

dataset_prepared_path: ./prepared-datasets/llama-3.2-reflection-coder
output_dir: ./out/llama-3.2-reflection-coder

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

micro_batch_size: 16
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5
warmup_ratio: 0.2

train_on_inputs: false
group_by_length: false
bf16: auto

gradient_checkpointing: true
logging_steps: 1
flash_attention: true

eval_steps: 1000
eval_table_size: 2
eval_batch_size: 2
eval_sample_packing: false
eval_max_new_tokens: 1024

special_tokens:
  pad_token: <|end_of_text|>