base_model: microsoft/Phi-3-mini-128k-instruct
trust_remote_code: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
chat_template: phi_3

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: rajpurkar/squad_v2
    type: squad:phi

dataset_prepared_path: ./prepared-datasets/squad
val_set_size: 16
output_dir: ./lora-out/squad
shuffle_before_split: true

sequence_len: 8192
sample_packing: false
pad_to_sequence_len: false

adapter: lora
lora_model_dir:
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:

gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 100
optimizer: adamw_torch
adam_beta2: 0.95
adam_epsilon: 0.00001
max_grad_norm: 1.0
lr_scheduler: cosine
learning_rate: 2e-6

train_on_inputs: false
group_by_length: false
bf16: auto

seed: 1010101

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: True
early_stopping_patience: 3
logging_steps: 1
flash_attention: true

eval_steps: 100
save_steps: 5000
eval_table_size: 16
eval_batch_size: 2
eval_sample_packing: false
eval_max_new_tokens: 64
eval_causal_lm_metrics: ["perplexity", "ter"]
do_causal_lm_eval: true

warmup_ratio: 0.2
debug: true
weight_decay: 0.1
resize_token_embeddings_to_32x: true
special_tokens:
  pad_token: "<unk>"
  additional_special_tokens: ["<document>", "<question>"]
