base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
chat_template: chatml

is_llama_derived_model: true

load_in_8bit: true
load_in_4bit: false
strict: false

rl: dpo
datasets:
  - path: argilla/ultrafeedback-binarized-preferences
    split: train
    type: chatml.argilla

dataset_prepared_path: ./prepared-datasets/distilabel-intel-orca-dpo-pairs
val_set_size: 0.05
output_dir: ./tinyllama-1.1b-slimorca-dpo

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: false

adapter: lora
lora_model_dir:

lora_r: 256
lora_alpha: 128
lora_dropout: 0.05
lora_target_linear: true
lora_modules_to_save:
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj


wandb_project: tinyllama-distilabel-intel-orca-dpo-pairs

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
adam_beta2: 0.95
adam_epsilion: 0.00001
lr_scheduler: linear
learning_rate: 1.414e-5

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
gradient_checkpoint_kwargs:
  use_reentrant: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps:
eval_table_size:
eval_table_max_new_tokens: 128
save_steps: 45
debug:
deepspeed:
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:
save_safetensors: true

dataloader_num_workers: 16
dataloader_pin_memory: true
