base_model: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: true
load_in_4bit: false
strict: false

rl: dpo
datasets:
  - path: roborovski/glaive-tool-usage-dpo
    type: chatml.intel
    split: train
    conversation: chatml_glaive

dataset_prepared_path: ./prepared-datasets/glaive-tool-usage-dpo
val_set_size: 0.01
output_dir: ./lora-out/tinyllama-function-calling-dpo

warmup_steps: 10
eval_steps: 1000
eval_table_size: 2
eval_batch_size: 1
eval_sample_packing: false
eval_max_new_tokens: 64
eval_causal_lm_metrics: ["sacrebleu", "comet", "ter", "chrf"]
do_causal_lm_eval: true

sequence_len: 4096
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 128
lora_alpha: 128
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj


wandb_project: tinyllama-glaive-tool-usage-dpo
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 3
optimizer: paged_adamw_8bit
lr_scheduler: linear
learning_rate: 1.4e-5

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
gradient_checkpoint_kwargs:
  use_reentrant: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention: true
flash_attention: true

saves_per_epoch: 1
debug:
weight_decay: 0.0
special_tokens:
seed: 42
